return {
	cmd = { "ruff", "server" },
	filetypes = { "python" },
	root_markers = { "pyproject.toml", "ruff.toml", ".ruff.toml", ".git" },
	settings = {
		-- Settings can be found here: https://docs.astral.sh/ruff/editors/settings/
		fixAll = true,
		organizeImports = true,
		showSyntaxErrors = true,
		logLevel = "info",
		lint = {
			enable = true,
			select = { "E4", "E7", "E9", "F" },
			extendSelect = {
				"ANN",
				"ARG",
				"B",
				"BLE",
				"C4",
				"DOC",
				"EXE",
				"FAST",
				"I",
				"ICN",
				"INP",
				"ISC",
				"N",
				"NPY",
				"PD",
				"PGH",
				"PIE",
				"PT",
				"Q",
				"RET",
				"RSE",
				"RUF",
				"S",
				"SIM",
				"TC",
				"TID",
				"W",
			},
			ignore = { "E402", "B905" },
		},
	},
	single_file_support = true,
	-- log_level = vim.lsp.protocol.MessageType.Warning,
}
